apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ehrs01"
  annotations:
    github.com/project-slug: hirveakshata/azure-functionapp-workflow # Change the value to your github repo which contains terraform code.
    backstage.io/techdocs-ref: dir:.
    azure.com/microsoft-web-sites: "ehrs01"
  title: "ehrs01" # you can give any title
  description: "Testing" # Change Description accordingly
  tags: ["azure-functionapp"]
spec:
  type: Infrastructure service
  owner: user:guest
  lifecycle: "Experimental"

